#!/bin/zsh
# If the gitconfig example file do not exists, we're standing in the wrong
# directory and can not setup the git configuration.
if ! [ -f 'git/gitconfig.symlink.example' ]; then
    return;
fi;

# We only need to setup git if the correct symlink file do not exists.
if ! [ -f 'git/gitconfig.symlink' ]; then
    # Retrieve the name for the git author.
    echo 'What is your git author name?';
    read GIT_AUTHOR_NAME;

    # Retrieve the email for the git author.
    echo 'What is your git author email?';
    read GIT_AUTHOR_EMAIL;

    # Replace the `AUTHOR_NAME` and `AUTHOR_EMAIL` with the user supplied
    # information in the symlink version of the file.
    sed -e "s/AUTHOR_NAME/$GIT_AUTHOR_NAME/g"\
        -e "s/AUTHOR_EMAIL/$GIT_AUTHOR_EMAIL/g"\
        "git/gitconfig.symlink.example" > "git/gitconfig.symlink";
fi;
