#!/usr/bin/env zsh
BREW=$(which brew 2> /dev/null)
if [ $? -eq 1 ]; then
    echo "homebrew does not seem to be installed."
    exit 1
fi

# checking whether package is already installed.
$BREW list -1 | grep -q "^$1\$"
if [ $? -eq 1 ]; then
    echo "installing $1 via homebrew."
    $BREW install $1 > /dev/null
fi
exit 0
