#!/usr/bin/env zsh
which brew > /dev/null 2>&1;
if [ $? -eq 0 ]; then
    exit 0
fi

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
if [ $? -eq 1 ]; then
    exit 1
fi
rehash
exit 0
